name: Build, Zip and Push Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        python -m PyInstaller --clean shuffler.spec
    
    - name: Zip the distribution
      run: |
        powershell -Command "Compress-Archive -Path .\dist\* -DestinationPath release.zip -Force"

    - name: Commit and push changes
      run: |
        git pull
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add built distribution"
        git push https://${{ secrets.PAT }}@github.com/JeffSinsel/SaveStateShuffler.git HEAD:main